backend:
  #name: test-repo
  name: github
  repo: aeiris/webesfeira

media_folder: /public/media
public_folder: /media

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: /src/content/posts
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }

  - name: blogposts
    label: Blog Posts
    label_singular: Blog Post
    folder: /src/content/blog
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }

  - name: tags
    label: Tags
    label_singular: Tag
    folder: /content/tags
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: richtext }

  - name: proxectos
    label: Proxectos
    label_singular: Proxecto
    folder: /content/proxectos
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Resumo, name: resumo, widget: richtext }
      - { label: País, name: pais, widget: richtext }
      - { label: Body, name: body, widget: richtext }

